name: Build And Publish Package

# 触发工作流程的事件
on:
  push:
    branches:
      - main

# 按顺序运行作业
jobs:
  publish-gpr:
    # 指定的运行器环境
    runs-on: ubuntu-latest
    # 设置 node 版本
    strategy:
      matrix:
        node-version: [16]
    steps:
      # 拉取 github 仓库代码
      - uses: actions/checkout@v3
      # 安装 pnpm
      - uses: pnpm/action-setup@v2
        with:
         version: 8.6.6
      # 设定 node 环境
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # 设置发包 npm 地址仓库
          registry-url: https://registry.npmjs.org
      # 安装依赖，相当于 npm ci
      - name: Install dependencies
        run: pnpm install
      # 执行构建步骤
      - name: 构建
        run: |
          pnpm run build
      # 执行部署
      # - name: 部署
      #   # 这个 action 会根据配置自动推送代码到指定分支
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     # 指定密钥，即在第一步中设置的
      #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     # 指定推送到的远程分支
      #     BRANCH: pages
      #     # 指定构建之后的产物要推送哪个目录的代码
      #     FOLDER: build
      - run: pnpm publish
        env:
          # 刚刚设置的 NPM_TOKEN
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
